export { StarterKit } from "@tiptap/starter-kit";
export { Highlight } from "@tiptap/extension-highlight";
export { TextAlign } from "@tiptap/extension-text-align";
export { TextStyle } from "@tiptap/extension-text-style";
export { Typography } from "@tiptap/extension-typography";
export { Dropcursor } from "@tiptap/extension-dropcursor";
export { Subscript } from "@tiptap/extension-subscript";
export { Superscript } from "@tiptap/extension-superscript";
export { Paragraph } from "@tiptap/extension-paragraph";
export { BulletList } from "@tiptap/extension-bullet-list";
export { OrderedList } from "@tiptap/extension-ordered-list";
export { TaskItem } from "@tiptap/extension-task-item";
export { TaskList } from "@tiptap/extension-task-list";
export { Table } from "@tiptap/extension-table";
export { TableCell } from "@tiptap/extension-table-cell";
export { TableHeader } from "@tiptap/extension-table-header";
export { TableRow } from "@tiptap/extension-table-row";
export { Underline } from "@tiptap/extension-underline";
export {Color} from "@tiptap/extension-color";

export { Heading } from "./Heading";
export { HorizontalRule } from "./HorizontalRule";
export { Document } from "./Document";
export { CodeBlock } from "./CodeBlock";
export { FontSize } from "./FontSize";
export { Columns, Column } from "./MultiColumn";
export { Link } from "./Link";
export { SlashCommand } from "./SlashCommand";
export { ClearStyles } from "./ClearStyles";
